// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoAS8iwJwYy24sUmmdeKIiinWBarfSwWE',
    appId: '1:747173595821:web:082905ca9b72a3fafa1424',
    messagingSenderId: '747173595821',
    projectId: 'uptimechamp',
    authDomain: 'uptimechamp.firebaseapp.com',
    storageBucket: 'uptimechamp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5SGY8JkBgF60VhRWnQMwHovq2PFzbALo',
    appId: '1:747173595821:android:97417b1015ed3e50fa1424',
    messagingSenderId: '747173595821',
    projectId: 'uptimechamp',
    storageBucket: 'uptimechamp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4eTR5kjKVu_AB_kAyadKCi4aoX0vNKh4',
    appId: '1:747173595821:ios:931d3232a33eb2c6fa1424',
    messagingSenderId: '747173595821',
    projectId: 'uptimechamp',
    storageBucket: 'uptimechamp.appspot.com',
    iosClientId: '747173595821-acf91ocoecfsqijld6otebipgmaud1k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.uptime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4eTR5kjKVu_AB_kAyadKCi4aoX0vNKh4',
    appId: '1:747173595821:ios:931d3232a33eb2c6fa1424',
    messagingSenderId: '747173595821',
    projectId: 'uptimechamp',
    storageBucket: 'uptimechamp.appspot.com',
    iosClientId: '747173595821-acf91ocoecfsqijld6otebipgmaud1k2.apps.googleusercontent.com',
    iosBundleId: 'com.example.uptime',
  );
}
